#%RAML 0.8
title: Foo Web API - Invalid Security Scheme
version: v1
protocols: [ HTTPS ]
baseUri: https://api.foo.com/{version}
mediaType: application/json
documentation:
  - title: Foo Web API Docs
    content: |
      Welcome to the _Foo Web API_ specification.
securitySchemes:
  - invalid-scheme:
      description: |
          Spotify supports OAuth 2.0 for authenticating all API requests.
      type: Invalid Scheme
