#%RAML 0.8
title: Spotify Web API
version: v1
protocols: [ HTTPS ]
baseUri: https://api.spotify.com/{version}
mediaType: application/json
/tracks:
  displayName: several-tracks
  post:
    body:
      application/json:
        schema: !include includes/post-playlist-schema.json
        example: !include includes/post-playlist-example.json
      application/x-www-form-urlencoded:
        formParameters:
          ids:
            displayName: Spotify Track IDs
            type: string
            description: A comma-separated list of IDs
            required: true
            example: '7ouMYWpwJ422jRcDASZB7P,4VqPOruhp5EdPBeR92t6lQ,2takcwOaAZWiXQijPHIx7B'
      multipart/form-data:
        formParameters:
          fooname:
            displayName: Foo Name
            type: string
            description: A name of foo
            required: true
            example: 'foobar baz'


