#%RAML 0.8
title: GitHub API
version: v3
baseUri: https://api.github.com
documentation:
 - title: Getting Started
   content: Dummy content on getting started
 - title: Basics of Authentication
   content: Dummy content on the basics of authentication
 - title: Rendering Data as Graphs
   content: Dummy content on rendering data as graphs
 - title: Overview
   content: !include includes/overview.md
